version: 2.1

orbs:
  # Replace this with your own!
  workflow: rhems-japan/workflow@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # "greet" is a sample command packaged with this orb config.
      # This sample integration test will run as long as the greet command exists. Once you remove the greet command you should remove this line.
      # Push new changes first, before adding new tests to your config.
      - workflow/update-submodule:
          module-name: orbs-workflow-subm
          # orbs-workflow-subm
          submodule-fingerprint: 89:9b:ce:5b:89:61:a8:4e:be:36:a8:45:63:f5:8f:2d
          # orbs-workflow
          master-fingerprint: d9:c7:15:84:5c:3c:86:5f:f5:ca:46:18:fd:7f:81:ce
      # - workflow/commit-filter:
      #     target-list: "alpha,master"
      #     stop-no-target: true
      # - workflow/call-workflow:
      #     org-or-user: "RHEMS-Japan"
      #     repo: "blue-mole-deploy"
      #     param: |
      #       { \"${CIRCLE_BRANCH}-blue-mole\": true }

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint: # Lint Yaml files
          filters:
            tags:
              only: /^test\/.*/
      - orb-tools/pack: # Pack orb source
          filters:
            tags:
              only: /^test\/.*/
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
          filters:
            tags:
              only: /^test\/.*/
      # optional: Run BATS tests against your scripts
      - bats/run:
          path: ./src/tests
          filters:
            tags:
              only: /^test\/.*/
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: rhems-japan/workflow
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          filters:
            tags:
              only: /^test\/.*/
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          filters:
            tags:
              only: /^test\/.*/
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-1:
          filters:
            tags:
              only: /^test\/.*/
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rhems-japan/workflow
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only:
                - master
                - main
            tags:
              only: /^test\/.*/
